# URL de connexion à la base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/basespring
# Identifiants de connexion base de données
spring.datasource.username=postgres
spring.datasource.password=maxime2003
# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver
# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuration de la sécurité pour les tests Postman
spring.security.user.name=admin
spring.security.user.password=admin

# JWT
jwt.secret=changeme-super-long-secret-key-for-jwt-signature
jwt.expiration=86400000

